### ISSUE TITLE
Doesn't work with node 0.12 http methods

### ISSUE THREAD

**Issue by aredridel** [tommymessbauer/hammock#14]
Since express calls the original http object's methods, you get errors like so:

```
_http_outgoing.js:174
  this.output.push(data);
             ^
TypeError: Cannot read property 'push' of undefined
    at ServerResponse.OutgoingMessage._buffer (_http_outgoing.js:174:14)
    at ServerResponse.OutgoingMessage._writeRaw (_http_outgoing.js:168:17)
    at ServerResponse.OutgoingMessage._send (_http_outgoing.js:123:15)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:557:16)
    at ServerResponse.res.send (/Users/ariastewart/Projects/adaro/node_modules/express/lib/response.js:188:10)
```

**Comment by tommymessbauer** [comment]
What version of express are you running?  

I don't actively use express anymore, but this should be a straight-forward drop in.  Early versions of express modified the native request and response objects which caused really bad issues.  By sending the version of express, we should be able to eliminate that first, then move on.  

Could you split this into a gist or unit test?  That would be ideal.

**Comment by tommymessbauer** [comment]
@Raynos - are you guys using this with express?

**Comment by Raynos** [comment]
@tommymessbauer I do not use express. Or node 0.12

**Comment by tommymessbauer** [comment]
@Raynos - Me neither.  

@aredridel - Can you create a test case or separate repo with the issue?  This could be any number of things depending on version of express or the test case.  

It seems weird at first look since hammock does not sub-class ServerResponse or OutGoingMessage so I cannot see how this example got into this stack trace.  With the little information available in this stack trace, it looks like you are not actually using MockResponse.

**Comment by aredridel** [comment]
That's the thing: It fails because it doesn't subclass. Express applies methods from ServerResponse to whatever it's given, so the internals have to match. `shop`'s implementation mostly works.

**Comment by aredridel** [comment]
This is in Express 4.x and 3.x that I'm actually using.

**Comment by tommymessbauer** [comment]
Node 0.12 is no longer in LTS so I'm gonna close this. If a PR comes in for the fix and it does not break a current LTS version, then I'll be happy to merge it.

https://github.com/nodejs/Release
